<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="responsibilityMetaModel" nsURI="http://www.example.org/responsibilityMetaModel"
    nsPrefix="responsibilityMetaModel">
  <eClassifiers xsi:type="ecore:EClass" name="Responsibility" eSuperTypes="#//Entity">
    <eOperations name="satisfied" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredResource" upperBound="-1"
        eType="#//resourceRequiredRelationship" eOpposite="#//resourceRequiredRelationship/responsibility"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="producedResource" upperBound="-1"
        eType="#//resourceProducedRelationship" eOpposite="#//resourceProducedRelationship/responsibility"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredActor" upperBound="-1"
        eType="#//actorRequiredRelationship" eOpposite="#//actorRequiredRelationship/responsibility"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="heldBy" upperBound="-1"
        eType="#//actorHoldsRelationship" eOpposite="#//actorHoldsRelationship/responsibility"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superResponsibility" upperBound="-1"
        eType="#//responsibilityRequiredRelationship" eOpposite="#//responsibilityRequiredRelationship/subRresponsibility"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subResponsibility" upperBound="-1"
        eType="#//responsibilityRequiredRelationship" eOpposite="#//responsibilityRequiredRelationship/superResponsibility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//Entity">
    <eOperations name="satisfied" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredBy" upperBound="-1"
        eType="#//resourceRequiredRelationship" eOpposite="#//resourceRequiredRelationship/resource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="producedBy" upperBound="-1"
        eType="#//resourceProducedRelationship" eOpposite="#//resourceProducedRelationship/resource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//Entity">
    <eOperations name="satisfied" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredBy" upperBound="-1"
        eType="#//actorRequiredRelationship" eOpposite="#//actorRequiredRelationship/actor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="heldResponsibility" upperBound="-1"
        eType="#//actorHoldsRelationship" eOpposite="#//actorHoldsRelationship/actor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eOperations name="getEntities" ordered="false" upperBound="-1" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsibilities" upperBound="-1"
        eType="#//Responsibility" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" upperBound="-1"
        eType="#//Actor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//Relation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" abstract="true" interface="true">
    <eOperations name="satisfied" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="satisifed" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="satisfactionCriteria" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="resourceRequiredRelationship" eSuperTypes="#//Relation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsibility" eType="#//Responsibility"
        eOpposite="#//Responsibility/requiredResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="#//Resource"
        eOpposite="#//Resource/requiredBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="resourceProducedRelationship" eSuperTypes="#//Relation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsibility" eType="#//Responsibility"
        eOpposite="#//Responsibility/producedResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="#//Resource"
        eOpposite="#//Resource/producedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="actorRequiredRelationship" eSuperTypes="#//Relation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsibility" eType="#//Responsibility"
        eOpposite="#//Responsibility/requiredActor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actor" eType="#//Actor"
        eOpposite="#//Actor/requiredBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="actorHoldsRelationship" eSuperTypes="#//Relation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsibility" eType="#//Responsibility"
        eOpposite="#//Responsibility/heldBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actor" eType="#//Actor"
        eOpposite="#//Actor/heldResponsibility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="responsibilityRequiredRelationship"
      eSuperTypes="#//Relation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subRresponsibility" eType="#//Responsibility"
        eOpposite="#//Responsibility/superResponsibility"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superResponsibility" eType="#//Responsibility"
        eOpposite="#//Responsibility/subResponsibility"/>
  </eClassifiers>
</ecore:EPackage>
